Do not overwrite auto.conf with contents of .config
The relevant difference is that .config uses quotes for string values
with spaces but automatically generated auto.conf does not use quotes.

This fixes following error that appears when trying to build out of
tree modules using akmods:

	2026/09/01 21:33:11 akmods: Building RPM using the command '/usr/sbin/akmodsbuild --kernels 6.18.42-3.rpi5.fc44.aarch64 /usr/src/akmods/aic8800d80-kmod.latest'
	+ LT_SYS_LIBRARY_PATH=/usr/lib64:
	+ export LT_SYS_LIBRARY_PATH
	+ CC=gcc
	+ export CC
	+ CXX=g++
	+ export CXX
	+ cd aic8800d80-kmod-0.20260824git2895da2
	+ for kernel_version in 6.18.42-3.rpi5.fc44.aarch64___/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64
	+ kver=6.18.42-3.rpi5.fc44.aarch64
	+ ksrc=/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64
	+ make V=1 -j4 -C _kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/aic8800 KVER=6.18.42-3.rpi5.fc44.aarch64 KDIR=/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64 modules
	make: Entering directory '/tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/aic
	8800'
	make -C /usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64 M=/tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.
	rpi5.fc44.aarch64/drivers/aic8800 ARCH=arm64 CROSS_COMPILE=  modules
	make[1]: Entering directory '/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64'
	make  -C /tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/aic8800 \
	-f /usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64/Makefile modules
	make[2]: Entering directory '/tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/
	aic8800'
	make --no-print-directory -C /tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/
	aic8800 \
	-f /usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64/Makefile modules
	/bin/sh: -c: line 1: syntax error near unexpected token `('
	/bin/sh: -c: line 1: `if [ "gcc (GCC) 16.2.1 20260819 (Red Hat 16.2.1-2)" != ""gcc (GCC) 16.2.1 20260819 (Red Hat 16.2.1-2)"" ]; then \'
	make[3]: *** [/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64/Makefile:1921: prepare] Error 2
	make[2]: *** [/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64/Makefile:248: __sub-make] Error 2
	make[2]: Leaving directory '/tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/a
	ic8800'
	make[1]: *** [Makefile:248: __sub-make] Error 2
	make[1]: Leaving directory '/usr/src/kernels/6.18.42-3.rpi5.fc44.aarch64'
	make: *** [Makefile:78: modules] Error 2
	make: Leaving directory '/tmp/akmodsbuild.1Yfi6c4c/BUILD/aic8800d80-kmod-0.20260824git2895da2-build/aic8800d80-kmod-0.20260824git2895da2/_kmod_build_6.18.42-3.rpi5.fc44.aarch64/drivers/aic8
	800'
	error: Bad exit status from /var/tmp/rpm-tmp.2rHYQ3 (%build)

	RPM build warnings:
		%source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from

	RPM build errors:
		Bad exit status from /var/tmp/rpm-tmp.2rHYQ3 (%build)